Bugfix --ssh-command and additional safety checks
--ssh-command and --key check to ensure no conflicting options occur.

diff --git a/git-idm b/git-idm
--- a/git-idm
+++ b/git-idm
@@ -41,10 +41,11 @@ Command options:
 
     active has no options
     add:
-                   ID - The first argument is the identity ID.
-          --name NAME - Name of the associated identity.
-        --email EMAIL - Email of the associated identity.
-            --key SSH_COMMAND - SSH private key of the associated identity.
+                               ID - The first argument is the identity ID.
+                      --name NAME - Name of the associated identity.
+                    --email EMAIL - Email of the associated identity.
+                    --key SSH_KEY - SSH private key of the associated identity.
+        --ssh-command SSH_COMMAND - Customize the SSH command ignoring --key
     list has no options.
     use:
         ID - Identity to activate.
@@ -135,13 +136,22 @@ while [[ $# -gt 0 ]]; do
             ;;
         --key)
             if [ ! -r "$2" ]; then
-                echo "ERROR: Private key ${2} does not exist."
+                echo "ERROR: Private key ${2} does not exist." >&2
+                exit 1
+            fi
+            if [ -n "${SSH_COMMAND}" ]; then
+                echo 'ERROR: --key conflicts with --ssh-command.  Use one or the other.' >&2
+                exit 1
             fi
             SSH_KEY="$2"
             SSH_COMMAND="ssh -i $2 -o IdentitiesOnly=yes -F /dev/null"
             shift 2
             ;;
         --ssh-command)
+            if [ -n "${SSH_KEY}" ]; then
+                echo 'ERROR: --ssh-command conflicts with --key.  Use one or the other.' >&2
+                exit 1
+            fi
             SSH_COMMAND="$2"
             shift 2
             ;;
@@ -201,8 +211,8 @@ case "${comm}" in
             echo 'ERROR: May not add an identity with the ID "all".  This is a reserved ID.' >&2
             exit 1
         fi
-        if ! identity_exists && [[ -z "${NAME}" || -z "${EMAIL}" || -z "${SSH_KEY}" ]]; then
-            echo 'ERROR: options --name, --email, and --key are required when adding an identity for the first time.' >&2
+        if ! identity_exists && [[ -z "${NAME}" || -z "${EMAIL}" || ( -z "${SSH_KEY}" && -z "${SSH_COMMAND}" ) ]]; then
+            echo 'ERROR: options --name, --email, and --key or --ssh-command are required when adding an identity for the first time.' >&2
             exit 1
         fi
         if [ -n "${NAME}" ]; then
@@ -213,8 +223,10 @@ case "${comm}" in
         fi
         if [ -n "${SSH_KEY}" ]; then
             git config --global gitidm."${id}".sshKey "${SSH_KEY}"
-            git config --global gitidm."${id}".sshCommand "${SSH_COMMAND}"
             check_ssh_agent "${SSH_KEY}"
+        fi
+        if [ -n "${SSH_COMMAND}" ]; then
+            git config --global gitidm."${id}".sshCommand "${SSH_COMMAND}"
         fi
         ;;
     help)
@@ -273,7 +285,9 @@ case "${comm}" in
             run_command git config --global core.sshCommand "${SSH_COMMAND}"
         fi
         run_command git config --global user.activeidm "${id}"
-        check_ssh_agent "${SSH_KEY}"
+        if [ -n "${SSH_KEY}" ]; then
+            check_ssh_agent "${SSH_KEY}"
+        fi
         ;;
     version)
         echo_version
